package com.vtmer.mapper;

import com.vtmer.domain.Administrator;
import java.util.List;

public interface AdministratorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    int insert(Administrator record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table administrator
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    List<Administrator> selectAll();
}