package com.vtmer.mapper;

import com.vtmer.domain.Interview;
import java.util.List;

public interface InterviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    int insert(Interview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table interview
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    List<Interview> selectAll();
}