package com.vtmer.mapper;

import com.vtmer.domain.Log;
import java.util.List;

public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Tue Aug 13 21:31:20 CST 2019
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Tue Aug 13 21:31:20 CST 2019
     */
    List<Log> selectAll();
}