package com.vtmer.mapper;

import com.vtmer.domain.Log;
import java.util.List;

public interface LogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    int insert(Log record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table log
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    List<Log> selectAll();
}