package com.vtmer.mapper;

import com.vtmer.domain.State;
import java.util.List;

public interface StateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    int insert(State record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    List<State> selectAll();
}