package com.vtmer.mapper;

import com.vtmer.domain.State;
import com.vtmer.domain.User;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
public interface StateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     * 添加
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    void insert(State record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table state
     * 查询所有
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    List<State> selectAll();

    /**
     * 删除
     * @param id
     */
    void delete(Integer id);

    /**
     * 更新
     * @param record
     */
    void update(State record);
}