package com.vtmer.mapper;

import com.vtmer.domain.User;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersss
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    boolean insert(User user);

    User selectOneByName(String username);

    boolean updateUserByName(User user);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usersss
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    List<User> selectAll();
}