package com.vtmer.domain;

public class Interview {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.id
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.user_id
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.written_examination
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    private String writtenExamination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.first_interview
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    private String firstInterview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.second_interview
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    private String secondInterview;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.first_assessment
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    private String firstAssessment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column interview.second_assessment
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    private String secondAssessment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.id
     *
     * @return the value of interview.id
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.id
     *
     * @param id the value for interview.id
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.user_id
     *
     * @return the value of interview.user_id
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.user_id
     *
     * @param userId the value for interview.user_id
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.written_examination
     *
     * @return the value of interview.written_examination
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public String getWrittenExamination() {
        return writtenExamination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.written_examination
     *
     * @param writtenExamination the value for interview.written_examination
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public void setWrittenExamination(String writtenExamination) {
        this.writtenExamination = writtenExamination == null ? null : writtenExamination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.first_interview
     *
     * @return the value of interview.first_interview
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public String getFirstInterview() {
        return firstInterview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.first_interview
     *
     * @param firstInterview the value for interview.first_interview
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public void setFirstInterview(String firstInterview) {
        this.firstInterview = firstInterview == null ? null : firstInterview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.second_interview
     *
     * @return the value of interview.second_interview
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public String getSecondInterview() {
        return secondInterview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.second_interview
     *
     * @param secondInterview the value for interview.second_interview
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public void setSecondInterview(String secondInterview) {
        this.secondInterview = secondInterview == null ? null : secondInterview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.first_assessment
     *
     * @return the value of interview.first_assessment
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public String getFirstAssessment() {
        return firstAssessment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.first_assessment
     *
     * @param firstAssessment the value for interview.first_assessment
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public void setFirstAssessment(String firstAssessment) {
        this.firstAssessment = firstAssessment == null ? null : firstAssessment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column interview.second_assessment
     *
     * @return the value of interview.second_assessment
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public String getSecondAssessment() {
        return secondAssessment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column interview.second_assessment
     *
     * @param secondAssessment the value for interview.second_assessment
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public void setSecondAssessment(String secondAssessment) {
        this.secondAssessment = secondAssessment == null ? null : secondAssessment.trim();
    }
}