package com.vtmer.domain;

import java.util.Date;

public class Log {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.admin_id
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.user_id
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.operational_record
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    private String operationalRecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.opreational_time
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    private Date opreationalTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.admin_id
     *
     * @return the value of log.admin_id
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.admin_id
     *
     * @param adminId the value for log.admin_id
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.user_id
     *
     * @return the value of log.user_id
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.user_id
     *
     * @param userId the value for log.user_id
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.operational_record
     *
     * @return the value of log.operational_record
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    public String getOperationalRecord() {
        return operationalRecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.operational_record
     *
     * @param operationalRecord the value for log.operational_record
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    public void setOperationalRecord(String operationalRecord) {
        this.operationalRecord = operationalRecord == null ? null : operationalRecord.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.opreational_time
     *
     * @return the value of log.opreational_time
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    public Date getOpreationalTime() {
        return opreationalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.opreational_time
     *
     * @param opreationalTime the value for log.opreational_time
     *
     * @mbg.generated Wed Aug 14 12:38:51 CST 2019
     */
    public void setOpreationalTime(Date opreationalTime) {
        this.opreationalTime = opreationalTime;
    }
}