package com.vtmer.domain;

import java.util.Date;

public class Log {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.id
     *
     * @mbg.generated Tue Aug 13 21:31:20 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.admi_id
     *
     * @mbg.generated Tue Aug 13 21:31:20 CST 2019
     */
    private Integer admiId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.opreational_time
     *
     * @mbg.generated Tue Aug 13 21:31:20 CST 2019
     */
    private Date opreationalTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column log.operational_content
     *
     * @mbg.generated Tue Aug 13 21:31:20 CST 2019
     */
    private String operationalContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.id
     *
     * @return the value of log.id
     *
     * @mbg.generated Tue Aug 13 21:31:20 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.id
     *
     * @param id the value for log.id
     *
     * @mbg.generated Tue Aug 13 21:31:20 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.admi_id
     *
     * @return the value of log.admi_id
     *
     * @mbg.generated Tue Aug 13 21:31:20 CST 2019
     */
    public Integer getAdmiId() {
        return admiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.admi_id
     *
     * @param admiId the value for log.admi_id
     *
     * @mbg.generated Tue Aug 13 21:31:20 CST 2019
     */
    public void setAdmiId(Integer admiId) {
        this.admiId = admiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.opreational_time
     *
     * @return the value of log.opreational_time
     *
     * @mbg.generated Tue Aug 13 21:31:20 CST 2019
     */
    public Date getOpreationalTime() {
        return opreationalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.opreational_time
     *
     * @param opreationalTime the value for log.opreational_time
     *
     * @mbg.generated Tue Aug 13 21:31:20 CST 2019
     */
    public void setOpreationalTime(Date opreationalTime) {
        this.opreationalTime = opreationalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column log.operational_content
     *
     * @return the value of log.operational_content
     *
     * @mbg.generated Tue Aug 13 21:31:20 CST 2019
     */
    public String getOperationalContent() {
        return operationalContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column log.operational_content
     *
     * @param operationalContent the value for log.operational_content
     *
     * @mbg.generated Tue Aug 13 21:31:20 CST 2019
     */
    public void setOperationalContent(String operationalContent) {
        this.operationalContent = operationalContent == null ? null : operationalContent.trim();
    }
}