package com.vtmer.domain;

public class State {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.id
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.first_volunteer
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    private String firstVolunteer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.second_volunteer
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    private String secondVolunteer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column state.user_id
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.id
     *
     * @return the value of state.id
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.id
     *
     * @param id the value for state.id
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.first_volunteer
     *
     * @return the value of state.first_volunteer
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public String getFirstVolunteer() {
        return firstVolunteer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.first_volunteer
     *
     * @param firstVolunteer the value for state.first_volunteer
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public void setFirstVolunteer(String firstVolunteer) {
        this.firstVolunteer = firstVolunteer == null ? null : firstVolunteer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.second_volunteer
     *
     * @return the value of state.second_volunteer
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public String getSecondVolunteer() {
        return secondVolunteer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.second_volunteer
     *
     * @param secondVolunteer the value for state.second_volunteer
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public void setSecondVolunteer(String secondVolunteer) {
        this.secondVolunteer = secondVolunteer == null ? null : secondVolunteer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column state.user_id
     *
     * @return the value of state.user_id
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column state.user_id
     *
     * @param userId the value for state.user_id
     *
     * @mbg.generated Mon Aug 12 19:58:57 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}