package com.vtmer.domain;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersss.id
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersss.user_head_img
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    private String userHeadImg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersss.user_name
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersss.user_sex
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    private String userSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersss.user_grade
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    private String userGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersss.user_college
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    private String userCollege;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersss.user_major
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    private String userMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersss.user_class
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    private String userClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersss.user_qq
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    private Integer userQq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersss.user_phone
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    private Integer userPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersss.user_wechar
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    private String userWechar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersss.user_first_volunteer
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    private String userFirstVolunteer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersss.user_second_volunteer
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    private String userSecondVolunteer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column usersss.user_self_introduction
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    private String userSelfIntroduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersss.id
     *
     * @return the value of usersss.id
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersss.id
     *
     * @param id the value for usersss.id
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersss.user_head_img
     *
     * @return the value of usersss.user_head_img
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public String getUserHeadImg() {
        return userHeadImg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersss.user_head_img
     *
     * @param userHeadImg the value for usersss.user_head_img
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public void setUserHeadImg(String userHeadImg) {
        this.userHeadImg = userHeadImg == null ? null : userHeadImg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersss.user_name
     *
     * @return the value of usersss.user_name
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersss.user_name
     *
     * @param userName the value for usersss.user_name
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersss.user_sex
     *
     * @return the value of usersss.user_sex
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public String getUserSex() {
        return userSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersss.user_sex
     *
     * @param userSex the value for usersss.user_sex
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public void setUserSex(String userSex) {
        this.userSex = userSex == null ? null : userSex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersss.user_grade
     *
     * @return the value of usersss.user_grade
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public String getUserGrade() {
        return userGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersss.user_grade
     *
     * @param userGrade the value for usersss.user_grade
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public void setUserGrade(String userGrade) {
        this.userGrade = userGrade == null ? null : userGrade.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersss.user_college
     *
     * @return the value of usersss.user_college
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public String getUserCollege() {
        return userCollege;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersss.user_college
     *
     * @param userCollege the value for usersss.user_college
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public void setUserCollege(String userCollege) {
        this.userCollege = userCollege == null ? null : userCollege.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersss.user_major
     *
     * @return the value of usersss.user_major
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public String getUserMajor() {
        return userMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersss.user_major
     *
     * @param userMajor the value for usersss.user_major
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public void setUserMajor(String userMajor) {
        this.userMajor = userMajor == null ? null : userMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersss.user_class
     *
     * @return the value of usersss.user_class
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public String getUserClass() {
        return userClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersss.user_class
     *
     * @param userClass the value for usersss.user_class
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public void setUserClass(String userClass) {
        this.userClass = userClass == null ? null : userClass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersss.user_qq
     *
     * @return the value of usersss.user_qq
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public Integer getUserQq() {
        return userQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersss.user_qq
     *
     * @param userQq the value for usersss.user_qq
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public void setUserQq(Integer userQq) {
        this.userQq = userQq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersss.user_phone
     *
     * @return the value of usersss.user_phone
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public Integer getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersss.user_phone
     *
     * @param userPhone the value for usersss.user_phone
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public void setUserPhone(Integer userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersss.user_wechar
     *
     * @return the value of usersss.user_wechar
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public String getUserWechar() {
        return userWechar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersss.user_wechar
     *
     * @param userWechar the value for usersss.user_wechar
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public void setUserWechar(String userWechar) {
        this.userWechar = userWechar == null ? null : userWechar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersss.user_first_volunteer
     *
     * @return the value of usersss.user_first_volunteer
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public String getUserFirstVolunteer() {
        return userFirstVolunteer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersss.user_first_volunteer
     *
     * @param userFirstVolunteer the value for usersss.user_first_volunteer
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public void setUserFirstVolunteer(String userFirstVolunteer) {
        this.userFirstVolunteer = userFirstVolunteer == null ? null : userFirstVolunteer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersss.user_second_volunteer
     *
     * @return the value of usersss.user_second_volunteer
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public String getUserSecondVolunteer() {
        return userSecondVolunteer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersss.user_second_volunteer
     *
     * @param userSecondVolunteer the value for usersss.user_second_volunteer
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public void setUserSecondVolunteer(String userSecondVolunteer) {
        this.userSecondVolunteer = userSecondVolunteer == null ? null : userSecondVolunteer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column usersss.user_self_introduction
     *
     * @return the value of usersss.user_self_introduction
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public String getUserSelfIntroduction() {
        return userSelfIntroduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column usersss.user_self_introduction
     *
     * @param userSelfIntroduction the value for usersss.user_self_introduction
     *
     * @mbg.generated Mon Aug 12 20:22:50 CST 2019
     */
    public void setUserSelfIntroduction(String userSelfIntroduction) {
        this.userSelfIntroduction = userSelfIntroduction == null ? null : userSelfIntroduction.trim();
    }
}